version: '3'
services:
  app:
    container_name: nodejs
    image: ocardenasg/node-cache
    restart: always
    build: .
    ports:
      - '5000:5000'
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=production
      - PORT=5000
    links:
      - redis
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
